# Oracle DB Connection Configuration (Service Name 사용 시 슬래시 / 사용)
db.driver=oracle.jdbc.OracleDriver
db.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
db.username=ojt_user
db.password=ojt1234

# Google SMTP Mail Configuration
smtp.host=smtp.gmail.com
smtp.port=465
smtp.username=cile0629@gmail.com
smtp.password=iowb wkmz szoe xgzb
