-- 1. 사용자 테이블 (USERS)
CREATE TABLE users (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username       VARCHAR2(50 CHAR) NOT NULL,
    password       VARCHAR2(255 CHAR) NOT NULL,
    name           VARCHAR2(50 CHAR),
    age            NUMBER(3),
    gender         VARCHAR2(10 CHAR),
    email          VARCHAR2(100 CHAR),
    phone_number   VARCHAR2(20 CHAR),
    address        VARCHAR2(255 CHAR),
    is_admin       NUMBER(1) DEFAULT 0 NOT NULL,
    is_manager     NUMBER(1) DEFAULT 0 NOT NULL,
    profile_img    VARCHAR2(300 CHAR) DEFAULT NULL,
    penalty_until  TIMESTAMP NULL,
    point          NUMBER DEFAULT 1000 NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_is_admin CHECK (is_admin IN (0, 1)),
    CONSTRAINT ck_users_is_manager CHECK (is_manager IN (0, 1))
);

-- 2. 매치 테이블 (MATCHES)
CREATE TABLE matches (
    match_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    field_name      VARCHAR2(100 CHAR) NOT NULL,
    highlight_video VARCHAR2(300 CHAR) DEFAULT NULL,
    match_at        TIMESTAMP NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    match_level     NUMBER(1) NOT NULL,
    gender          VARCHAR2(10 CHAR) DEFAULT 'ANY' NOT NULL,
    num_members     NUMBER(1) NOT NULL,

    CONSTRAINT pk_matches PRIMARY KEY (match_id),
    CONSTRAINT ck_matches_match_level CHECK (match_level BETWEEN 0 AND 10),
    CONSTRAINT ck_matches_gender CHECK (gender IN ('MALE', 'FEMALE', 'ANY')),
    CONSTRAINT ck_matches_num_members CHECK (num_members > 0)
);

-- 3. 자유 게시판 테이블 (BOARD)
CREATE TABLE board (
    board_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    writer_id  NUMBER NOT NULL,
    title      VARCHAR2(200 CHAR) NOT NULL,
    content    CLOB NOT NULL,
    file_uuid  VARCHAR2(300 CHAR) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_board PRIMARY KEY (board_id),
    CONSTRAINT fk_board_writer FOREIGN KEY (writer_id) REFERENCES users (user_id)
);

-- 4. 공지사항 테이블 (NOTICE)
CREATE TABLE notice (
    notice_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    writer_id  NUMBER NOT NULL,
    title      VARCHAR2(200 CHAR) NOT NULL,
    content    CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_notice PRIMARY KEY (notice_id),
    CONSTRAINT fk_notice_writer FOREIGN KEY (writer_id) REFERENCES users (user_id)
);

-- 5. 첨부 파일 메타데이터 테이블 (FILES)
CREATE TABLE files (
    file_uuid         VARCHAR2(300 CHAR) NOT NULL,
    original_filename VARCHAR2(300 CHAR) NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_files PRIMARY KEY (file_uuid)
);

-- 6. 이메일 인증 테이블 (EMAIL_VERIFICATIONS)
CREATE TABLE email_verifications (
    verification_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id         NUMBER DEFAULT NULL,
    email           VARCHAR2(100 CHAR) NOT NULL,
    auth_code       VARCHAR2(6 CHAR) NOT NULL,
    expired_at      TIMESTAMP NOT NULL,
    verified        NUMBER(1) DEFAULT 0 NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_email_verifications PRIMARY KEY (verification_id),
    CONSTRAINT fk_email_verifications_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT ck_email_verifications_verified CHECK (verified IN (0, 1))
);

-- 7. 구장 테이블 (GROUND)
CREATE TABLE ground (
    ground_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    manager_id       NUMBER NOT NULL,
    name             VARCHAR2(100 CHAR) NOT NULL,
    address          VARCHAR2(255 CHAR) NOT NULL,
    address_detail   VARCHAR2(100 CHAR),
    region           VARCHAR2(50 CHAR),
    size_info        VARCHAR2(50 CHAR),
    is_indoor        NUMBER(1) DEFAULT 0 NOT NULL,
    grass_type       VARCHAR2(30 CHAR) DEFAULT '인조잔디',
    parking_type     NUMBER(1) DEFAULT 0 NOT NULL,
    has_shower       NUMBER(1) DEFAULT 0 NOT NULL,
    has_lights       NUMBER(1) DEFAULT 1 NOT NULL,
    has_shoes_rental NUMBER(1) DEFAULT 0 NOT NULL,
    has_ball_rental  NUMBER(1) DEFAULT 0 NOT NULL,
    price_per_hour   NUMBER DEFAULT 0 NOT NULL,
    notice           CLOB,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_ground PRIMARY KEY (ground_id),
    CONSTRAINT fk_ground_manager FOREIGN KEY (manager_id) REFERENCES users (user_id) ON DELETE CASCADE
);

-- 8. 포인트 결제 테이블 (POINT_PAYMENT)
CREATE TABLE point_payment (
    payment_id        VARCHAR2(50) PRIMARY KEY,
    user_id           NUMBER NOT NULL,
    amount            NUMBER NOT NULL,
    status            VARCHAR2(20) DEFAULT 'READY' NOT NULL,
    pg_transaction_id VARCHAR2(50),
    point_applied     NUMBER(1) DEFAULT 0 NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at      TIMESTAMP
);

-- 9. 목업 PG 결제 테이블 (MOCK_PG_PAYMENT)
CREATE TABLE mock_pg_payment (
    pg_transaction_id VARCHAR2(50) PRIMARY KEY,
    payment_id        VARCHAR2(50) NOT NULL,
    amount            NUMBER NOT NULL,
    status            VARCHAR2(20) NOT NULL,
    approved_at       TIMESTAMP
);

-- 10. 매치 신청 테이블 (MATCH_APPLICATION)
CREATE TABLE match_application (
    application_id VARCHAR2(50) PRIMARY KEY,
    match_id       VARCHAR2(50) NOT NULL,
    user_id        NUMBER NOT NULL,
    fee            NUMBER NOT NULL,
    status         VARCHAR2(20) NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 11. 매치 참가자 테이블 (MATCH_PARTICIPANTS)
CREATE TABLE match_participants (
    participant_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id       VARCHAR2(50) NOT NULL,
    user_id        NUMBER NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);




